name: Build distribution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Python setup
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.x'
      
      - name: Check style
        run: python -m pip install flake8 && flake8 bluetti_mqtt

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build distributions
        run: python -m build

      - name: Publish to Test PyPI
        if: github.repository == 'olexandrkucher/bluetti_mqtt'
        uses: pypa/gh-action-pypi-publish@release/v1.10
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip_existing: true
          repository_url: https://test.pypi.org/legacy/

      - name: Publish tagged to PyPI
        if: github.repository == 'olexandrkucher/bluetti_mqtt' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}